version: '3.8'

services:
  pgdb:
    image: postgres:16
    restart: always
    networks:
      - maillog
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=maillog
    ports:
      - "5532:5432"
    volumes:
      - pgdb-data1:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - maillog
    command: [ "api:run" ]
    ports:
      - "30060:80"
    depends_on:
      - pgdb
    env_file:
      - .env.docker
    volumes:
      - ./data:/opt/app/data

networks:
  maillog:
    external: true

volumes:
  pgdb-data1:
